replicaCount: 1

image:
  repository: "jenkins/jenkins"
  pullPolicy: IfNotPresent
  tag: "lts-jdk11"


container:
  port: 8080

storageClassName: local-storage
volume:
  name: jenkins-pv
  mountPath: /var/jenkins_home

persistentVolume:
  size: 1Gi
  path: /var/tmp

persistentVolumeClaim:
  storageSize: 1Gi


service:
  name: jenkins
  type: NodePort
  port: 80
  protocol: TCP
  nodePort: 30001
  targetPort: 8080

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  #targetMemoryUtilizationPercentage: 80