apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Value.pvName }}
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: {{ .Value.pvSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Value.pvPath }}
