apiVersion: v1
kind: PersistentVolumeClaim
metadata:
     name: {{ .Value.pvcName }}
spec:
  storageClassName: {{ .Value.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Value.pvcStorageSize }}
