apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: {{ .Values.service.type }}
  selector:
    app: jenkins
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}              #serviceport
    targetPort: {{ .Values.service.targetPort }}      #container port
    nodePort: {{ .Values.service.nodePort }}       #nodeport
