apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Value.storageClassName }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
