apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.name }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: {{ .Values.persistentVolume.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistentVolume.path }}
