apiVersion: v1
kind: PersistentVolumeClaim
metadata:
     name: jenkins-pvc
spec:
  storageClassName: local-storage
  dataSource:
    name: jenkins-pv
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storageSize }}
