apiVersion: v1
kind: PersistentVolumeClaim
metadata:
     name: jenkins
spec:
  storageClassName: local-storage
  dataSource:
    name: mypv1
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
