apiVersion: v1
kind: PersistentVolumeClaim
metadata:
     name: {{ .Values.persistentVolumeClaim.name }}
spec:
  storageClassName: local-storage
  dataSource:
    name: {{ .Values.persistentVolume.name }}
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storageSize }}
