apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - name: myport1
    protocol: TCP
    port: 80              #serviceport
    targetPort: 8080      #container port
    nodePort: 30000       #nodeport
